version: 2

sources:
  - name: raw
    schema: gz_raw_data
    description: greenweez raw data source
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: sales of greenweez / we have one row per product_id found in each order_id
        columns:
          - name: "(orders_id || '-' || pdt_id)"
            description: primary key of the table
            tests:
              - unique
              - not_null
      - name: product
        identifier: raw_gz_product
        description: purchase_price by products_id
        columns:
          - name: products_id
            description: primary key of the table
            tests:
              - unique
      - name: ship
        identifier: raw_gz_ship
        description: ship_price by orders_id
        columns:
          - name: orders_id
            description: primary key of the table
            tests:
              - unique
      - name: adwords
        identifier: raw_gz_adwords
        description: campaign in adwords
        columns:
          - name: "(date_date || '-' || campaign_key)"
            description: primary key of the table
            tests:
              - unique
      - name: bing
        identifier: raw_gz_bing
        description: campaign in bing
        columns:
          - name: "(date_date || '-' || campaign_key)"
            description: primary key of the table
            tests:
              - unique
      - name: criteo
        identifier: raw_gz_criteo
        description: campaign in criteo
        columns:
          - name: "(date_date || '-' || campaign_key)"
            description: primary key of the table
            tests:
              - unique
      - name: facebook
        identifier: raw_gz_facebook
        description: campaign in facebook
        columns:
          - name: "(date_date || '-' || campaign_key)"
            description: primary key of the table
            tests:
              - unique

models:
  - name: int_campaigns
    description: "Table intermédiaire unifiée de toutes les campagnes publicitaires."
    columns:
      - name: date_date
        description: "Date de la campagne"
      - name: paid_source
        description: "Source d'achat (adwords, bing, criteo, facebook)"
      - name: campaign_key
        description: "Identifiant unique de la campagne"
      - name: campaign_name
        description: "Nom de la campagne"
      - name: ads_cost
        description: "Coût de la publicité (FLOAT64)"
      - name: impression
        description: "Nombre d’impressions"
      - name: click
        description: "Nombre de clics"
  - name: campaigns_day
    description: "Table agrégée par jour des performances de campagnes (coût, impressions, clics)."
    columns:
      - name: (campaign_key || '-' || date_date)
        description: "Jour de l'agrégation."
        tests:
          - unique
          - not_null
      - name: nb_campaigns
        description: "Nombre de campagnes distinctes ce jour-là."
      - name: total_ads_cost
        description: "Coût total des campagnes du jour."
      - name: total_impressions
        description: "Nombre total d'impressions."
      - name: total_clicks
        description: "Nombre total de clics."
  - name: finance_campaigns_day
    description: >
      Mart quotidien combinant les metrics financières et publicitaires
      pour la finance (inclut marge opérationnelle, coût pub, quantités, revenus, etc.)
    columns:
      - name: date
        description: Date du reporting (jour)
        tests:
          - not_null
      - name: ads_margin
        description: "Marge après publicité : operational_margin - ads_cost"
      - name: average_basket
        description: "Panier moyen"
      - name: operational_margin
        description: "Marge opérationnelle"
      - name: ads_cost
        description: "Coût total des campagnes pubs"
      - name: ads_impression
        description: "Total impressions pubs"
      - name: ads_clicks
        description: "Total clics pubs"
      - name: quantity
        description: "Total produits vendus"
      - name: revenue
        description: "Revenu total du jour"
      - name: purchase_cost
        description: "Coût d'achat total du jour"
      - name: margin
        description: "Marge brute"
      - name: shipping_fee
        description: "Total frais de port"
      - name: log_cost
        description: "Total coûts logistiques"
      - name: ship_cost
        description: "Total ship_costs"